name: Deploy ALGORITMIT Trading Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Lint code
      run: npm run lint

  build-docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          your-dockerhub/algoritmit-trading-bot:latest
          your-dockerhub/algoritmit-trading-bot:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  release:
    needs: build-docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: ALGORITMIT Trading Bot v${{ github.run_number }}
        body: |
          ## 🚀 ALGORITMIT Trading Bot Release v${{ github.run_number }}
          
          ### What's New
          - Automated deployment
          - Docker container support
          - Enhanced monitoring
          - Bug fixes and improvements
          
          ### Installation
          ```bash
          # One-line installer
          curl -fsSL https://raw.githubusercontent.com/${{ github.repository }}/main/install.sh | bash
          
          # Docker installation
          docker-compose up -d
          ```
          
          ### Quick Start
          1. Run the installer
          2. Configure your settings
          3. Start trading!
          
          For detailed instructions, see the [README](https://github.com/${{ github.repository }}#readme).
        draft: false
        prerelease: false